### PR TITLE
Update protocolcheck.js

### PR DESCRIPTION
**Pull request by kirill-konshin**
Closes #30
Closes #16

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Bump!

**Comment by kirill-konshin** [comment]
Bump!

**Comment by kirill-konshin** [comment]
Ping!!!

**Comment by ismailhabib** [comment]
Could you please create a Pull Request to the original repo? Thanks!

**Comment by kirill-konshin** [comment]
Something must have gone wrong... Made another PR #33.

**Pull request merged**
